#!/bin/bash
WID=$(xdotool getactivewindow)
gnome-terminal --title "emoji picker" --wait -- /bin/sh -c '_STR=$(fzf < ~/scripts/emoji-list); printf "%s" ${_STR%% *} > ~/scripts/currentemoji'
xdotool windowactivate --sync $WID

if [[ $( xprop -id $WID | grep "WM_CLASS(STRING)" ) == *"firefox"* ]]; then
#  firefox is slow as shit
  xdotool type --delay 500 "$(cat ~/scripts/currentemoji)"; echo
else
  xdotool type "$(cat ~/scripts/currentemoji)"; echo
fi
sleep 1
rm ~/scripts/currentemoji
